version: 2

models:
  - name: dim_dates
    description: "Dimensão de datas utilizada para análises temporais da camada Gold."

    columns:
      - name: date_id
        description: "Chave única da data no formato YYYYMMDD."
        tests:
          - unique
          - not_null

      - name: full_date
        description: "Data completa no formato date."
        tests:
          - unique
          - not_null

      - name: year
        description: "Ano da data."
        tests:
          - not_null

      - name: month
        description: "Número do mês da data."
        tests:
          - not_null

      - name: quarter
        description: "Trimestre da data."
        tests:
          - not_null

      - name: year_month
        description: "Ano e mês da data no formato YYYY-MM."
        tests:
          - not_null

  - name: dim_customers
    description: "Dimensão com os dados cadastrais e geográficos dos clientes."

    columns:
      - name: customer_id
        description: "Identificador do cliente associado ao pedido."
        tests:
          - unique
          - not_null

      - name: customer_unique_id
        description: "Identificador utilizado para reconhecer o mesmo cliente em pedidos diferentes."
        tests:
          - not_null

      - name: zip_code
        description: "Prefixo do CEP do cliente."
        tests:
          - not_null

      - name: city
        description: "Cidade do cliente."

      - name: state
        description: "Estado do cliente."

      - name: latitude
        description: "Latitude média associada ao CEP do cliente."

      - name: longitude
        description: "Longitude média associada ao CEP do cliente."
