version: 2

models:
  - name: bronze_orders
    description: "Pedidos com tipos de dados convertidos"
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - not_null

  - name: bronze_customers
    description: "Clientes com CEP convertido para texto"
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: customer_unique_id
        tests:
          - not_null

  - name: bronze_order_items
    description: "Itens dos pedidos"
    columns:
      - name: order_id
        tests:
          - not_null
      - name: order_item_id
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null
      - name: seller_id
        tests:
          - not_null

  - name: bronze_order_payments
    description: "Pagamentos dos pedidos"
    columns:
      - name: order_id
        tests:
          - not_null
      - name: payment_sequential
        tests:
          - not_null

  - name: bronze_order_reviews
    description: "Avaliações dos pedidos"
    columns:
      - name: review_id
        tests:
          - not_null
      - name: order_id
        tests:
          - not_null

  - name: bronze_products
    description: "Produtos com medidas físicas"
    columns:
      - name: product_id
        tests:
          - unique
          - not_null

  - name: bronze_sellers
    description: "Vendedores"
    columns:
      - name: seller_id
        tests:
          - unique
          - not_null

  - name: bronze_geolocation
    description: "Dados de geolocalização por CEP"
    columns:
      - name: geolocation_zip_code_prefix
        tests:
          - not_null

  - name: bronze_product_category_translation
    description: "Tradução de categorias de produtos"
    columns:
      - name: product_category_name
        tests:
          - unique
          - not_null